---
title: "NGOs_Final_Inshallah"
output: html_document
---

#Installing Packages

```{r}
library(xtable)
library(stargazer)
install.packages("irr")
library(irr)
library(caret)
library(plyr)
install.packages("jtools")
library(jtools)
install.packages("ggstance")
library(ggstance)
library(dplyr)
```

#Reading Data

```{r}
final_data <- read.csv("final_data.csv")


```

#Selecting Main Variables

```{r}
final_data_final <- final_data %>% select(Main.Frame,Language, Education, Health, Security, Women.s.Rights, Article.Type, date_2, Article.Size, Negative, pa, gr, dg, protest)

final_data_final <- final_data_final %>% mutate(Education = as.factor(Education)) %>% mutate(Security = as.factor(Security)) %>% mutate(Health = as.factor(Health)) %>% mutate(Women.s.Rights = as.factor(Women.s.Rights))
```

# Turning Variables into Factors.

```{r}
final_data_final$Education <- recode_factor(final_data_final$Education, "1" =  "No", "2" = "Yes")                   
final_data_final$Health <- recode_factor(final_data_final$Health, "1" =  "No", "2" = "Yes")                   
final_data_final$Security <- recode_factor(final_data_final$Education, "2" =  "No", "3" = "Yes")                   
#final_data_final$Negative <- recode_factor(final_data_final$Education, "0" =  "No", "1" = "Yes")                   
final_data_final$Public_Accountability <- recode_factor(final_data_final$pa, "0" =  "No", "1" = "Yes")
final_data_final$Government_Resistance <- recode_factor(final_data_final$gr, "0" =  "No", "1" = "Yes") 
final_data_final$Doing_Good <- recode_factor(final_data_final$dg, "0" =  "No", "1" = "Yes")                   
final_data_final$Protest <- recode_factor(final_data_final$protest, "0" =  "No", "1" = "Yes")                   
final_data_final$Women.s.Rights <- recode_factor(final_data_final$Women.s.Rights, "1" =  "No", "2" = "Yes")                   
summary(final_data_final$Security)
```
# Descriptive Statistics


```{r}

stargazer(final_data_final, type = "text", title="Descriptive statistics", digits=1, out="table1.txt")

stargazer(table(final_data_final), type="text")



```

#Running Regressions on Models.


```{r}

reg_2 <- glm(Negative~ Language +  Education  + Health  + Women.s.Rights   + Article.Type +   as.numeric(date_2) + Article.Size , family=binomial(link='logit') ,data = final_data_final)



reg_3 <- glm(pa ~ Language +  Education  + Health  + Women.s.Rights   + Article.Type +   as.numeric(date_2) + Article.Size , family=binomial(link='logit') ,data = final_data_final)


reg_4 <- glm(dg ~  Language +  Education  + Health  + Women.s.Rights   + Article.Type +  + as.numeric(date_2) + Article.Size , family=binomial(link='logit') ,data = final_data_final)


reg_5 <- glm(gr ~  Language +  Education  + Health  + Women.s.Rights  + Article.Type +  + as.numeric(date_2) + Article.Size , family=binomial(link='logit') ,data = final_data_final     )


reg_6 <- glm(protest ~   Language +  Education  + Health  + Women.s.Rights  + Article.Type +  + as.numeric(date_2) + Article.Size , family=binomial(link='logit') ,data = final_data_final  )


```


# Exporting Stargazer tables of regression and descriptive statistics.


```{r}
stargazer(reg_2, out = "neg_reg.html")
stargazer(reg_3, reg_4, reg_5, reg_6, out = "frames_reg.html")

print(xtable(round(prop.table(table(final_data$Language, final_data$Negative),1),2)), type = "html", file = "sent_mean.html")

print(xtable(round( 100 * prop.table(table( final_data_final$Main.Frame, final_data_final$Language),2),0 )), type = "html", file = "main_frame.html")

print(xtable(t(rbind.data.frame(lapply(final_data_final[,c(9, 2:5, 14:17)], table)))), type = "html", file = "covariates.html")


table(final_data_final$date_2)

print(xtable(t(table(final_data_final$date_2))), type = "html", file = "years.html")
```


Plotting and Visualizing Results 

```{r}

plot_summs(reg_2, reg_3, reg_4, reg_5, reg_6, exp = TRUE, model.names = c("Negative", "Doing Good", "Public Accountability", "Government Resistance", "Protest"),  omit.coefs = c("(Intercept)", "EducationYes", "HealthYes", "Women.s.RightsYes", "as.factor(Security)3", "Article.TypeEditorial", "Article.SizeEqual to A4", "Article.SizeHalf A4", "Article.SizeLess than half A4", "Article.SizeMore than A4", "as.numeric(date_2)", coefs = c("LanguageUrdu"  = "Urdu"))) +  ylab("Language: Urdu") + xlab("Odds Ratio") 



```


# Asessing Inter-coder Reliability

```{r}
inter_coder_data_filtered <- read.csv("inter_coder_data_filtered.csv")


kappa2(cbind.data.frame(inter_coder_data_filtered$Negative, inter_coder_data_filtered$Negative.1))
agree(cbind.data.frame(inter_coder_data_filtered$Negative, inter_coder_data_filtered$Negative.1))

       
kappa2(cbind.data.frame(inter_coder_data_filtered$Main.Frame, inter_coder_data_filtered$Main.Frame.1))
agree(cbind.data.frame(inter_coder_data_filtered$Main.Frame, inter_coder_data_filtered$Main.Frame.1))



```

# Assessing Newspaper Sentiment by various Newspaper Sources.

```{r}

View(ddply(final_data, .(Newspaper), summarize,  Negative=round(100 *mean(as.numeric(Negative)), 2)))

final_data %>% group_by(Newspaper) %>% mutate(number = n())

```


